- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: install mongodb-org
    ansible.builtin.package:
      name: mongodb
      state: present
  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: copy mongo.repo
    ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/mongod.conf
  - name: restart mongod
    ansible.builtin.service:
       name: mongod
       state: restarted